server:
  port: ${PORT:21000}

spring:
  application:
    name: taole
  datasource:
    url: jdbc:mysql://114.115.251.174:13306/taole?useSSL=false
    username: taole
    password: Z##kUK5nFb$&c2WXn89%pLRE34MI1VYP
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  mail:
    host: smtp.aliyun.com
    username: vampire3019@aliyun.com
    password: SongLinhao3019!
    sender: vampire3019@aliyun.com
    reciever: linhao.song@welian.com



# 日志设置
logging.file: logs/${spring.application.name}.log
logging:
  level:
    org.demon: info
    org.demon.advice: debug
    org.demon.taole.mapper: error


